name: Streamfox.Server

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] # os: [macOS-latest, ubuntu-latest, windows-latest]
    steps:
    - name: Setup .NET Core if needed
      uses: actions/setup-dotnet@v1.4.0
      with:
        dotnet-version: '3.1.102'
      if: matrix.os == 'macOS-latest' || matrix.os == 'ubuntu-latest' # Broken on windows if you try to install .NET Core, as it already exists
    - uses: actions/checkout@master
    - name: Build
      run: dotnet build ./Streamfox.Server.sln --configuration Release
    - name: Test
      run: dotnet test ./Streamfox.Server.sln --configuration Release
